[package]
name = "yyzyreconn"
version = "0.1.0"
edition = "2021"

[dependencies]
systray = "0.4.0"
webbrowser = "0.5.5"
textcode = "0.1.2"
hotkey = "0.3.1"
simplelog = "^0.10.0"
log = "0.4.14"

[build-dependencies]
winres = "0.1"
